name: Publish Python distributions to PyPI and TestPyPI

on:
  workflow_run:
    workflows: ["OpenGHG tests"]
    types:
      - completed
  push:
    branches: master

jobs:
  build-and-publish:
    name: Build and publish Python distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: |
          pip install --upgrade build
        if: startsWith(github.ref, 'refs/tags')
      - name: Build a binary wheel and a source tarball
        run: | 
          python -m build --sdist --wheel --outdir dist/ .
        if: startsWith(github.ref, 'refs/tags')
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}      